# Generated by Django 5.2.6 on 2025-09-04 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='song',
            table='Music',
        ),
    ]
